# -*- coding: utf-8 -*-
"""car_price_decision_tree_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqUuAkM4Wq20NNzTRu2AFp7hPa6CrYBH

#IMPORT LIBRARY
"""

!pip install category-encoders

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import category_encoders as ce

"""# CONNECT GOOGLE DRIVE"""

from google.colab import drive
drive.mount('/content/drive')

"""#LOAD DATA"""

df = pd.read_csv('/content/drive/MyDrive/Car details v3.csv')

print("Jumlah data:", df.shape)
print("\n5 data pertama:")
df.head()

"""# EKSPLORASI DATA"""

df['fuel'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribusi Jenis Bahan Bakar')
plt.ylabel('')
plt.show()

df['transmission'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribusi Transmisi')
plt.ylabel('')
plt.show()

df['owner'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribusi Kepemilikan')
plt.ylabel('')
plt.show()

"""# DATA CLEANING"""

# Bersihkan kolom mileage
df['mileage'] = df['mileage'].str.replace('kmpl', '', regex=False)
df['mileage'] = df['mileage'].str.replace('km/kg', '', regex=False)
df['mileage'] = pd.to_numeric(df['mileage'], errors='coerce')

# Bersihkan kolom engine
df['engine'] = df['engine'].str.replace('CC', '', regex=False)
df['engine'] = pd.to_numeric(df['engine'], errors='coerce')

# Bersihkan kolom max_power
df['max_power'] = df['max_power'].str.replace('bhp', '', regex=False)
df['max_power'] = pd.to_numeric(df['max_power'], errors='coerce')

# Bersihkan nama kolom (hapus spasi)
df.columns = df.columns.str.strip().str.lower()

print("Kolom setelah dibersihkan:", df.columns.tolist())

df.head()

#membersihkan kolom torque & tambah fitur
def extract_torque_rpm(x):
    try:
        x = str(x).lower().replace(',', '')
        numbers = re.findall(r'\d+\.?\d*', x)
        torque = float(numbers[0])
        if 'kgm' in x:
            torque *= 9.8
        rpm_min = float(numbers[1]) if len(numbers) >= 2 else None
        rpm_max = float(numbers[2]) if len(numbers) >= 3 else rpm_min
        return torque, rpm_min, rpm_max
    except:
         return np.nan, np.nan, np.nan

df[['torque_clean', 'rpm_min', 'rpm_max']] = df['torque'].apply(
    lambda x: pd.Series(extract_torque_rpm(x))
)

# Hapus kolom yang tidak dipakai
df = df.drop(columns=['torque', 'name'])

df['car_age'] = 2026 - df['year']
df['km_per_year'] = df['km_driven'] / (df['car_age'] + 1)
df['power_to_engine'] = df['max_power'] / df['engine']

print("Kolom sekarang:", df.columns.tolist())

print("Missing value SEBELUM diisi:")
print(df.isnull().sum())

for col in df.select_dtypes(include='number').columns:
    df[col] = df[col].fillna(df[col].median())

print("\n Missing value SETELAH diisi:")
print(df.isnull().sum())

"""# HAPUS OUTLIER"""

sebelum = len(df)

Q1 = df['selling_price'].quantile(0.25)
Q3 = df['selling_price'].quantile(0.75)
IQR = Q3 - Q1

batas_bawah = Q1 - 2.5 * IQR
batas_atas  = Q3 + 2.5 * IQR

# Hanya simpan data yang tidak terlalu ekstrem
df = df[(df['selling_price'] >= batas_bawah) & (df['selling_price'] <= batas_atas)]

sesudah = len(df)
print(f"Data sebelum: {sebelum} baris")
print(f"Data sesudah hapus outlier: {sesudah} baris")
print(f"Outlier yang dihapus: {sebelum - sesudah} baris")

"""#AMBIL FEATURE (X) & TARGET (y)"""

X = df.drop('selling_price', axis=1)

y = np.log1p(df['selling_price'])

print("Bentuk X:", X.shape)
print("Bentuk y:", y.shape)

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.hist(df['selling_price'], bins=50, color='salmon')
plt.title('Distribusi Harga Asli')
plt.xlabel('Harga')

plt.subplot(1, 2, 2)
plt.hist(y, bins=50, color='skyblue')
plt.title('Distribusi Harga (Log Transform)')
plt.xlabel('Log Harga')

plt.tight_layout()
plt.show()

"""# SPLIT DATA (70% TRAINING, 30% TESTING)"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=15
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

"""#Label Encoding & Scaling

"""

numeric_features = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X_train.select_dtypes(include=['object', 'category']).columns.tolist()

print("Fitur numerik  :", numeric_features)
print("Fitur kategori :", categorical_features)

# Pipeline numerik
numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', RobustScaler())
])

# Pipeline kategori
categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Gabungan
preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_features),
    ('cat', categorical_pipeline, categorical_features)
])

# Model Decision Tree
pipeline_dt = Pipeline([
    ('preprocessor', preprocessor),
    ('model', DecisionTreeRegressor(random_state=15))
])

"""# HPO GridSearch"""

param_grid = {
    'model__max_depth': [5, 8, 10, 12, 15],
    'model__min_samples_split': [2, 5, 10, 15, 20],
    'model__min_samples_leaf': [1, 2, 3, 4, 5],
    'model__criterion': ['squared_error', 'friedman_mse']
}

grid_dt = GridSearchCV(
    pipeline_dt,
    param_grid,
    cv=5,
    scoring='r2',
    verbose=1,
    n_jobs=-1
)

grid_dt.fit(X_train, y_train)

print("Best Params:", grid_dt.best_params_)
print("Best R2 CV:", round(grid_dt.best_score_, 4))

"""# Evaluasi R², MSE, RMSE"""

y_pred = grid_dt.predict(X_test)

r2  = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("=" * 40)
print(f"R2 Score : {r2:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")
print("=" * 40)

# Visualisasi
plt.figure(figsize=(7, 5))
plt.scatter(y_test, y_pred, alpha=0.4, color='steelblue', label='Prediksi')
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    color='red',
    linewidth=2,
    label='Ideal'
)

plt.xlabel("Harga Aktual (Log)")
plt.ylabel("Harga Prediksi (Log)")
plt.title(f"Actual vs Predicted | R² = {r2:.4f}")
plt.legend()
plt.tight_layout()
plt.show()

"""# VISUALISASI DECISION TREE"""

import graphviz
from sklearn import tree

# ambil model terbaik
decision_tree_model = grid_dt.best_estimator_.named_steps['model']

# ambil nama fitur
feature_names = grid_dt.best_estimator_.named_steps['preprocessor'].get_feature_names_out()

# export ke DOT
dot_data = tree.export_graphviz(
    decision_tree_model,
    out_file=None,
    feature_names=feature_names,
    filled=True,
    rounded=True
)

# tampilkan
graph = graphviz.Source(dot_data)
graph

"""# SAVE MODEL"""

# Simpan model Decision Tree
import joblib

joblib.dump(
    grid_dt.best_estimator_,
    '/content/drive/MyDrive/car_price_decision_tree_model_update.sav'
)

print("✅ Model Decision Tree berhasil disimpan!")